# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 21:21
from __future__ import unicode_literals

import base64, io
from django.db import migrations, models
from django.db.models import Q
from PIL import Image

def forwards_func(apps, schema_editor):
    """Initialize `Attachment`.`data_uri` as needed"""
    Attachment = apps.get_model('forallbackpack', 'Attachment')

    for attachment in Attachment.objects.exclude(Q(file='') | Q(data_uri__gt='')):
        try:
            image = Image.open(attachment.file)
            image_format = image.format
            
            if image_format in ('GIF', 'JPEG', 'JPG', 'PNG'):
                thumbnail = image.copy()
                image.thumbnail((300, 300), Image.ANTIALIAS)
                
                buffer = io.BytesIO()
                image.save(buffer, format=image_format)
                
                data_uri = 'data:image/%s;base64,%s' % (
                    image_format.lower(),
                    base64.b64encode(buffer.getvalue())
                ) 
                
                buffer.close()
                
                attachment.data_uri = data_uri
                attachment.save()
            
            image.close()        
        except IOError:
            pass
            

class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0041_auto_20170912_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='data_uri',
            field=models.TextField(blank=True, help_text='Data URL for image thumbnails'),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
